# Example for provisioning an instance of a GCP service.
# In this case this example is for Google PubSub service.
# As all instances and bindings, created in gcp-instances
# namespace. Parameters are "topic" and "subscription".
apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: gcp-pubsub-instance
  namespace: gcp-instances
spec:
  serviceClassName: pubsub
  planName: default
  parameters:
    resources:
    - name: my-topic
      type: pubsub.v1.topic
      properties:
        topic: my-topic
    - name: my-subscription
      type: pubsub.v1.subscription
      properties:
        subscription: my-subscription
        topic: "$(ref.my-topic.name)"
